apiVersion: v1
kind: Secret
metadata:
  name: demo-db-secret
type: Opaque
stringData:
  DB_HOST: demo-postgres
  DB_PORT: "5432"
  DB_NAME: demodb
  DB_USER: postgres
  DB_PASSWORD: <YOUR_DB_PASSWORD>
