name: prod-java-on-eks
on: 
  push: 
    branches: [main]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running manually'
        required: false
        default: 'Manual health check'

permissions:
  id-token: write
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: java-demo-app
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          cache: 'maven'
          distribution: temurin
          java-version: '21'

      - name: build and test the app
        run: mvn clean verify

      - name: config aws creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ID }}:role/github-actions-role
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag the image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}'
          # format: 'sarif'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
      - name : Push image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      
      - name: Checkout infra repo
        uses: actions/checkout@v7
        with:
          repository: 'BhupeshDahiya/prod-java-on-eks'
          token: ${{ secrets.GH_TOKEN }}
          path: infra

      - name: Update image tag in manifest
        env:
          IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
        run: |
          sed -i "s|image:.*java-demo-app.*|image: $IMAGE|" infra/gitops/manifests/java_demo_app/deployment.yaml

      - name: Commit and push
        run: |
          cd infra
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add gitops/manifests/java_demo_app/deployment.yaml
          git commit -m "ci: update java-demo-app image to ${{ github.sha }}"
          git push